const Services = [
    {
        Id: '1',
        sImg:'/images/service/1.jpg',
        sIcon:'/images/icon/kitchen-utensils.png',
        slug:'Central Garbage Point',
        sTitle: 'Garbage Point',
        description:"These are large containers that are built for multiple waste streams and are positioned in a central location. The garbage trucks empty them when they're full",
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '2',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/gas-stove.png',
        slug:'Gas-Line-Services',
        sTitle: 'Gas Line Services',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '3',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'Waste Collection',
        sTitle: 'Waste (Garbage) Collection',
        description:"This means transporting solid waste from the point of use and disposal to the point of treatment or landfill. Our customers call us when their garbage cans are full, and we empty them on a daily, weekly, or monthly basis.",
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '4',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'Enviromental Design',
        sTitle: 'Enviromental Design',
        description:'We begin with an on-site consultation to assess the requirements for and the state of your property.Our full-service landscaping "design-build-Install-Maintain" company offers imaginative landscape designs, top-notch installations, and trustworthy expert landscape care.This service includes drip irrigation, creating public and highway routes, landscaping for roundabouts, and water pumping for irrigation.From concept sketches to final designs, our in-house team of talented landscape designers will create the layout for your home, place of business, or institution that you have always imagined. Implementing the design is the last phase.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '5',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/basement.png',
        slug:'Grass Cutting (Mowing)',
        sTitle: 'Grass Cutting (Mowing)',
        description:'This includes using a slasher or mowing equipment to level the grass or trims it down. Regardless of the size of the area, our landscapers complete it beautifully and quickly.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/remodeling.png',
        slug:'Fumigation',
        sTitle: 'Fumigation',
        description:'This entails the elimination of dangerous microorganisms by completely filling a space with gaseous insecticides, also known as fumigants, in order to suffocate or poison the pests present. We utilize it to eradicate pests from soil, grain, food, buildings (structural fumigation), and other areas.We carry out fumigation procedures in accordance with the highest standards of quality and safety.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/remodeling.png',
        slug:'Estate & Commercial Cleaning',
        sTitle: 'Estate & Commercial Cleaning',
        description:"Cleaning is essential to maintaining a healthy work atmosphere, which is good for employees and can help your company draw in new clients and customers, whether you run a small business or a big office.We facilitate business cleaning while promoting a healthier indoor environment for workers and guests.For a variety of establishments and enterprises, we provide commercial cleaning solutions, including:businesses, educational facilities, retail stores, and governmental structures.We offer the following commercial cleaning services: vacuuming carpets and flooring, mopping tile floors, and dusting flat surfaces, shelves, and workstations. clean surfaces with a lot of touches, empty trash cans, clean restrooms for staff and visitors,The extra efforts we make and the services we provide set us apart from other office cleaning services.",
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/remodeling.png',
        slug:'Supply of Cleaning and waste management equipment',
        sTitle: 'Supply of Cleaning and waste management equipment',
        description:'Any business, institution, or organization needs the proper cleaning and waste management tools. The appropriate ones will enable you to save time and guarantee the effectiveness and cleanliness of your place.We provide our customers with tools including dustbins, trash bags, brooms, brushes, gloves, etc.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    }
]


export default Services;